### ISSUE TITLE
Relative links on Index pages

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-content-mirror#11]
I found a problem with links on the 2009 awards on the bottom of this page: http://oii-test.navnorth.com/what-we-do/teacher-quality/transition-to-teaching/awards/

It looks like there are relative links (href=ca.html) that we need to replace with the external content URL when it ends with ```index.html``` or ```index.htm``` or just ```/```

so right now we end up with the California link going to ```http://www2.ed.govca.html/``` when it should go to ```http://www2.ed.gov/programs/transitionteach/2009abstracts/ca.html```

**Comment by joehobson** [comment]
when you finish your work-day, let me know the status of this issue and when we should expect a fix. I need to send an updated plugin to the host but decided to wait until this was fixed.

**Comment by johnpaulbalagolan** [comment]
fixed #11 with my latest source commit to github

**Comment by joehobson** [comment]
I think you need another check for links that start with non-alpha characters (especially ```/``` and ```.../```)

For instance, on this page there's a link to Awards: http://oii-test.navnorth.com/what-we-do/teacher-quality/transition-to-teaching/applicant-info-and-eligibility/

That server doesn't have the plugin update yet, so the link goes to http://www2.ed.gov/programs/transitionteach/awards.html, but on my local dev (with latest code) the link gets updated to http://www2.ed.gov/programs/transitionteach//programs/transitionteach/awards.html

also keep in mind that we shouldn't just be looking for links to htm and html files... what about pdf or php? So really it would be an href that starts with alphanumeric that's not http or mailto, so that you can fix any of the following:

 * mypage.html
 * some_directory/page.php
 * downloads/myfile.pdf

**Comment by johnpaulbalagolan** [comment]
I have committed another fix to the relative links in github. Kindly try it on your end sir. Not sure if you got my SMS earlier. My daughter got sick. So I was just able to commit the updated code.

Thanks.

**Comment by joehobson** [comment]
looks like that fixed it. Thanks for getting on this at such a late hour. I did get your text earlier. Hope your daughter is feeling better.
