### ISSUE TITLE
Removing all external content items

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-content-mirror#12]
Got a bug report from OII admins that they couldn't remove external content items on a page. When I looked into it, I found that when there were 2 items on a page and you remove both, and Update... both would still be there on reload. But if you removed 1 it would update okay.

Please check the update process to make sure you can remove 1 or both or all and still save changes. You should also be able to add a page with no external items and have it save (without saving an empty one... since that will then get queued into the scraper with an empty URL). I'd say for new pages don't put a new/empty external content item in until they click the "New" button to load it. 

This is low priority. I told them how to workaround the issue for now. Not expecting this to be updated until the current GAT issues are complete. thanks

**Comment by johnpaulbalagolan** [comment]
fixed #12 with the latest source code committed to github
