### ISSUE TITLE
Fix relative links when processing imported content

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-content-mirror#3]
When extracting content from external sources, we need to replace relative links so that they still work correctly when displayed. Here's an example of a test page where I noticed the issue: http://oii-test.navnorth.com/initiatives-and-projects/arts/arts-in-education-national-program/applicant-info-eligibility/

I'd suggest putting it in a utility function, just in case we need it elsewhere and so it's easier to test and track changes. Things to be mindful of:

 * relative links that don't start with a forward slash will be harder (eg.. href="../downloads/xx.ppt" or href="downloads/xx.ppt")
 * they use many mailto links so test with those
 * http:// versus https://

This is a lower priority issue, so address it after the other requests. Thanks

**Comment by johnpaulbalagolan** [comment]
hi Sir,

I have committed my latest code for the relative links to fix #3. Please test it when you get a chance. I've tested it with the link provided above and it worked fine.

Thanks.
