### ISSUE TITLE
order field gone

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-content-mirror#7]
Looks like we can't order content items anymore. When I looked back through the code, the order field disappeared with this commit - https://github.com/navnorth/wp-content-mirror/commit/f91cde7d9534bf3a05421d90c9958f0615c05d4e

**Comment by johnpaulbalagolan** [comment]
Hi Sir,

It should still be working. I moved the order to post meta. I have tested it both locally and on the test site and it works just fine.

Btw, I fixed a bug of the last content meta arrow direction as it should suppose to point upward but it shows downward on first load. I have fixed it in my latest commit.

Thanks.
