### ISSUE TITLE
links between mirrored pages 

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-content-mirror#8]
There are some mirrored pages where the content pulled in has a link to another mirrored page, but of course without processing the link will go to the old site. Here's an example, the link to Applicant info at the end of the paragraph: http://oii-test.navnorth.com/what-we-do/innovation/ready-to-learn-television-rtl/

I'd like you to try and add a function to the process where it looks for links in the external content, tries to find a match in our mirrored pages, and changes the link to point at our internal page. One possible issue would be if we mirrored the same external page on 2 different internal pages. Probably not very common, if ever, so just use the first one if that happens.

**Comment by johnpaulbalagolan** [comment]
fixed #8 with the latest committed code to github. replaced internal links with equivalent mirrored page
