### ISSUE TITLE
debug mode setting

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-content-mirror#9]
Add a debug mode checkbox on the Settings page so that we can easily turn debugging on and off. It looks like the plugin is having the same trouble on the ED test server that it did on ours - imports content when called on demand, but is not pulling in all pages on the hourly schedule. We need to be able to troubleshoot it to find out what's wrong. 

After you add the debug setting, go back through the debug stuff I added before and switch it to the new plugin setting, and add more as necessary so we can see what's happening, so we have a log when pages are updated.

**Comment by johnpaulbalagolan** [comment]
fixed #9 with latest code committed in github
